name: dart_websocket_client1
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 < 3.0.0'

dependencies:
  web_socket_channel: ^2.2.0
  json_annotation:  ^4.6.0
  json_serializable: ^6.3.1
#  socket_io: ^1.0.1
#  socket_io_client: ^2.0.0
#  html: ^0.15.0

dev_dependencies:
  lints: ^2.0.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

